decimalmain: decimalmain.o decimal.o
	g++ -o decimalmain decimal.o

decimalmain.o: decimalmain.c decimal.h
	g++ -o decimalmain.o decimalmain.c -c

decimal.o: decimal.c decimal.h
	g++ -o decimal.o decimal.c -c